import db from '../db.js';

;(async () => {
  try {
    await db.schema.dropTableIfExists('farms')
    await db.schema.withSchema('public').createTable('farms', (table) => {
      table.increments('id').unique().notNullable()
      table.string('SiteInfor').notNullable()
      table.string('Country').notNullable()
      table.float('Latitude').notNullable()
      table.float('Longitude').notNullable()
      table.float('Elevation').notNullable()
      table.integer('MAT')
      table.integer('MAP')
      table.string('ClimateType')
      table.string('SamplingDepth')
      table.string('SamplingThickness')
      table.integer('SandPerc')
      table.integer('SiltPerc')
      table.integer('ClayPerc')
      table.string('Texture')
      table.integer('SoilpH')
      table.string('CoverCrop').notNullable()
      table.string('CoverCropGroup').notNullable()
      table.string('GrainCrop').notNullable()
      table.string('GrainCropGroup').notNullable()
      table.string('Tillage_C')
      table.string('Tillage_T')
      table.string('Fertilization_C')
      table.string('Fertilization_T')
      table.string('Conservation_Type')
      table.string('ControlDescription')
      table.integer('Yield_C')
      table.integer('Yield_T')
      table.integer('Weed_C')
      table.integer('Weed_T')
      table.timestamps(true, true)
    })
    console.log('farms table created!')
    process.exit(0)
  } catch (err) {
    console.log(err)
    process.exit(1)
  }
})()

